# Trage hier deinen OpenAI API Key ein
openai_api_key = "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"
